import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import pinoHttp from 'pino-http';
import authRoutes from './routes/authRoutes';
import { prisma } from './utils/prisma';
import { errorHandler } from './middleware/errorHandler';
import studentRoutes from './routes/studentRoutes';
import applicationRoutes from './routes/applicationRoutes';
const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.CORS_ORIGIN ?? 'http://localhost:5173' }));
app.use(express.json({ limit: '1mb' }));
app.use(pinoHttp());
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 100 }));
app.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok' }, message: 'Application is running' }));
app.get('/ready', async (_req, res, next) => { try { await prisma.$queryRaw`SELECT 1`; res.json({ success: true, data: { status: 'ready', database: 'connected' }, message: 'Application is ready' }); } catch (error) { next(error); } });
app.use('/api/v1/auth', authRoutes);
app.use('/api/v1/students', studentRoutes);
app.use('/api/v1/applications', applicationRoutes);
app.use(errorHandler);
export default app;
