import { FormEvent, useState } from 'react';
import { Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { api } from './api/client';
const roles: Record<string,string> = { SUPER_ADMIN:'/admin/dashboard', AZAAM_STAFF:'/admin/dashboard', UNIVERSITY_USER:'/university/dashboard', ORGANIZATION_USER:'/organization/dashboard', SUPERVISOR:'/supervisor/dashboard', STUDENT:'/student/dashboard' };
function PublicHome(){return <main className="shell"><section className="panel"><div className="eyebrow">AZAAM International Medics Network</div><h1 className="title">Clinical training with a clearer path forward.</h1><p className="muted">A secure foundation for students, universities, host institutions, and supervisors.</p><button className="button" onClick={()=>location.href='/login'}>Sign in to platform</button></section></main>}
function Login(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const navigate=useNavigate();async function submit(event:FormEvent){event.preventDefault();setError('');try{const {data}=await api.post('/auth/login',{email,password});sessionStorage.setItem('azam_token',data.data.token);navigate(roles[data.data.user.roles[0]]??'/');}catch{setError('Unable to sign in with those credentials.');}}return <main className="shell"><section className="panel"><div className="eyebrow">Secure access</div><h1 className="title">Welcome back</h1><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="muted">{error}</p>}<button className="button">Sign in</button></form></section></main>}
function Dashboard({role}:{role:string}){return <><nav className="nav"><span className="brand">AZAAM / {role.replace('_',' ')}</span><button className="button" onClick={()=>{sessionStorage.removeItem('azam_token');location.href='/login'}}>Sign out</button></nav><main className="shell"><section className="panel"><div className="eyebrow">Operational workspace</div><h1 className="title">{role === 'STUDENT' ? 'Your attachment journey' : 'Your AZAAM dashboard'}</h1><p className="muted">Foundation dashboard connected to the authenticated platform session.</p><div className="grid"><div className="stat">Account status<strong>Active</strong></div><div className="stat">Permissions<strong>Scoped</strong></div><div className="stat">Next step<strong>Review</strong></div></div></section></main></>}
function Protected({role}:{role:string}){return sessionStorage.getItem('azam_token')?<Dashboard role={role}/>:<Navigate to="/login" replace/>}
export default function App(){return <Routes><Route path="/" element={<PublicHome/>}/><Route path="/login" element={<Login/>}/><Route path="/admin/dashboard" element={<Protected role="ADMIN"/>}/><Route path="/student/dashboard" element={<Protected role="STUDENT"/>}/><Route path="/university/dashboard" element={<Protected role="UNIVERSITY_USER"/>}/><Route path="/organization/dashboard" element={<Protected role="ORGANIZATION_USER"/>}/><Route path="/supervisor/dashboard" element={<Protected role="SUPERVISOR"/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
